variable "proxmox_host_ip" {
  type        = string
  description = "The base HOST of proxmox machine. The 'base' server where promox resides..."
  default     = "192.168.50.200"
}

variable "default_gateway" {
  type        = string
  description = "The base HOST of proxmox machine. The 'base' server where promox resides..."
  default     = "192.168.50.1"
}

variable "proxmox_endpoint" {
  type        = string
  description = "The full HTTPS URL API endpoint for the Proxmox VE host"
  default     = "https://192.168.50.200:8006/"
}

variable "proxmox_api_token" {
  type        = string
  description = "The complete concatenated Proxmox API token ID and Secret string"
  sensitive   = true # Mask this value out of standard CLI console log outputs
}

variable "k3s_share_token" {
  type        = string
  description = "The join token generated by the K3s control plane server"
  sensitive   = true # This prevents Terraform from printing the token to stdout during plan/apply
}