# Variables for Proxmox VM provisioning with Terraform and Packer
# ==============================================================================
# Packer needs its variables defined in its own .hcl file. They can share 
# The terraform.tfvars file, but the .hcl extension is for packer build variables, and command:
# This is a bit redundant, but its the more DRY way right now. See packer.pkrvars.hcl for the variables specific to packer builds.

variable "proxmox_endpoint" {
  type        = string
  description = "The full HTTPS URL API endpoint for the Proxmox VE host."
  default     = "https://192.168.50.200:8006/"
}

# Use this for Terraform
variable "proxmox_api_token" {
  type        = string
  description = "The complete concatenated Proxmox API token ID and Secret string."
  sensitive   = true
}

# Packer needs these as individual components
variable "proxmox_api_token_id" {
  type    = string
  default = "root@pam!packer"
}

variable "proxmox_api_token_secret" {
  type      = string
  sensitive = true
}

variable "proxmox_template_vm_id" {
  type        = string
  description = "The VM ID of the Proxmox template to clone for worker nodes."
  default     = "777"
}

variable "proxmox_node_name" {
  type        = string
  description = "The name of the Proxmox node to target for VM deployments."
  default     = "mothership"
}

# Having a bunch of IPs ins't ideal, but this is a quick and dirty way to get the job done without needing to write a custom script or Ansible playbook for this step.

variable "proxmox_host_ip" {
  type        = string
  description = "The IP address of the Proxmox host."
  default     = "192.168.50.200"
}


variable "k3s_manager_ip" {
  type        = string
  description = "The IP address of the K3s control manager node for worker registration. Match this IP with the KUBECONFIG"
  default     = "192.168.50.72"
}

variable "default_gateway_ip" {
  type        = string
  description = "The network default gateway."
  default     = "192.168.50.1"
}

variable "http_bind_address_ip" {
  type        = string
  description = "The IP of the machine from which packer hcl and terraform will be executed from."
  default     = "192.168.50.55"
}

variable "worker_count" {
  type        = number
  description = "The number of worker nodes to provision in the cluster."
  default     = 2
}

variable "k3s_share_token" {
  type        = string
  description = "The join token generated by the K3s control plane server."
  sensitive   = true
}